<a href="https://colab.research.google.com/github/danirles07/datascience/blob/main/RetoEmpleados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [35]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib as plt
import matplotlib.pyplot as plt
from google.colab import files

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
#Leer un archivo en tu drive
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Ing_caracteristicas/reto_ing_caracteristicas.csv')
df.head()

Age BusinessTravel              Department DistanceFromHome  Education  \
0   50  Travel_Rarely  Research & Development             1 km          2   
1   36  Travel_Rarely  Research & Development             6 km          2   
2   21  Travel_Rarely                   Sales             7 km          1   
3   52  Travel_Rarely  Research & Development             7 km          4   
4   33  Travel_Rarely  Research & Development            15 km          1   

  EducationField  EmployeeCount  EmployeeNumber  EnvironmentSatisfaction  \
0        Medical              1             997                        4   
1        Medical              1             178                        2   
2      Marketing              1            1780                        2   
3  Life Sciences              1            1118                        2   
4        Medical              1             582                        2   

  Gender  ...  PercentSalaryHike  PerformanceRating RelationshipSatisfaction  \
0   Male  ...                 22                  4                        3   
1   Male  ...                 20                  4                        4   
2   Male  ...                 13                  3                        2   
3   Male  ...                 19                  3                        4   
4   Male  ...                 12                  3                        4   

   StandardHours TotalWorkingYears  TrainingTimesLastYear  WorkLifeBalance  \
0             80                32                      1                2   
1             80                 7                      0                3   
2             80                 1                      3                3   
3             80                18                      4                3   
4             80                15                      2                4   

  YearsInCurrentRole YearsSinceLastPromotion Attrition  
0                  4                       1        No  
1                  2                       0        No  
2                  0                       1       Yes  
3                  6                       4        No  
4                  6                       7       Yes  

[5 rows x 30 columns]

In [4]:
EmpleadosAttrition = df
EmpleadosAttrition.columns.tolist()

['Age',
 'BusinessTravel',
 'Department',
 'DistanceFromHome',
 'Education',
 'EducationField',
 'EmployeeCount',
 'EmployeeNumber',
 'EnvironmentSatisfaction',
 'Gender',
 'JobInvolvement',
 'JobLevel',
 'JobRole',
 'JobSatisfaction',
 'MaritalStatus',
 'MonthlyIncome',
 'NumCompaniesWorked',
 'HiringDate',
 'Over18',
 'OverTime',
 'PercentSalaryHike',
 'PerformanceRating',
 'RelationshipSatisfaction',
 'StandardHours',
 'TotalWorkingYears',
 'TrainingTimesLastYear',
 'WorkLifeBalance',
 'YearsInCurrentRole',
 'YearsSinceLastPromotion',
 'Attrition']

In [5]:
EmpleadosAttrition.dtypes

Age                          int64
BusinessTravel              object
Department                  object
DistanceFromHome            object
Education                    int64
EducationField              object
EmployeeCount                int64
EmployeeNumber               int64
EnvironmentSatisfaction      int64
Gender                      object
JobInvolvement               int64
JobLevel                     int64
JobRole                     object
JobSatisfaction              int64
MaritalStatus               object
MonthlyIncome                int64
NumCompaniesWorked           int64
HiringDate                  object
Over18                      object
OverTime                    object
PercentSalaryHike            int64
PerformanceRating            int64
RelationshipSatisfaction     int64
StandardHours                int64
TotalWorkingYears            int64
TrainingTimesLastYear        int64
WorkLifeBalance              int64
YearsInCurrentRole           int64
YearsSinceLastPromotion      int64
Attrition                   object
dtype: object

In [6]:
#Eliminar las columnas que no tiene relación con los cálculos
EmpleadosAttrition.drop(['EmployeeCount','EmployeeNumber','Over18','StandardHours'], axis = 1, inplace = True)

In [7]:
#Calcular los años desde la contratación

#Transformar la columna de fecha en tipo date

EmpleadosAttrition['Year'] = EmpleadosAttrition['HiringDate'].str[-4:]

In [8]:
#Crear columna de años en la compañia hasta el 2018

EmpleadosAttrition['Year'] = EmpleadosAttrition['Year'].astype(int)
EmpleadosAttrition['YearsAtCompany'] = 2018 - EmpleadosAttrition['Year']

In [9]:
#Renombrar la variable DistanceFromHome

EmpleadosAttrition['DistanceFromHome_km'] = EmpleadosAttrition['DistanceFromHome']

#Crear la nueva variable distanceFromHome que solo contenga numeros

EmpleadosAttrition['DistanceFromHome']=EmpleadosAttrition['DistanceFromHome_km'].str[:-2]
EmpleadosAttrition['DistanceFromHome']=EmpleadosAttrition['DistanceFromHome'].astype(int)

In [10]:
#Generar una tabla con los sueldos promedio
SueldoPromedioDepto = EmpleadosAttrition.groupby('Department')['MonthlyIncome'].mean()
SueldoPromedioDepto

Department
Human Resources           6239.888889
Research & Development    6804.149813
Sales                     7188.250000
Name: MonthlyIncome, dtype: float64

In [11]:
#Normalizar la variable de Monthly income

#Importar las librerias
from sklearn.preprocessing import MinMaxScaler

#Iniciar el MinMaxScaler
scaler = MinMaxScaler()

#Escalar la variable
EmpleadosAttrition['MonthlyIncome_norm']=scaler.fit_transform(EmpleadosAttrition[['MonthlyIncome']])

In [12]:
#Comprobar que funciono la normalizacion
EmpleadosAttrition['MonthlyIncome_norm'].describe()

count    400.000000
mean       0.311196
std        0.258308
min        0.000000
25%        0.106939
50%        0.222711
75%        0.462745
max        1.000000
Name: MonthlyIncome_norm, dtype: float64

In [13]:
#Convertir la variable categorica en numérica

#Importar OneHotEncode

from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(sparse_output=False)

#Encode Business Travel
encoded_businesstravel = encoder.fit_transform(EmpleadosAttrition[['BusinessTravel']])
encoded_df_businesstravel = pd.DataFrame(encoded_businesstravel, columns=encoder.get_feature_names_out(['BusinessTravel']))

#Encode Department
encoded_department = encoder.fit_transform(EmpleadosAttrition[['Department']])
encoded_df_department = pd.DataFrame(encoded_department, columns=encoder.get_feature_names_out(['Department']))

#Encode EducationField
encoded_educationfield = encoder.fit_transform(EmpleadosAttrition[['EducationField']])
encoded_df_educationfield = pd.DataFrame(encoded_educationfield, columns=encoder.get_feature_names_out(['EducationField']))

#Encode Gender
encoded_gender = encoder.fit_transform(EmpleadosAttrition[['Gender']])
encoded_df_gender = pd.DataFrame(encoded_gender, columns=encoder.get_feature_names_out(['Gender']))

#Encode JobRole
encoded_jobrole = encoder.fit_transform(EmpleadosAttrition[['JobRole']])
encoded_df_jobrole = pd.DataFrame(encoded_jobrole, columns=encoder.get_feature_names_out(['JobRole']))

#Encode MaritalStatus
encoded_maritalstatus = encoder.fit_transform(EmpleadosAttrition[['MaritalStatus']])
encoded_df_maritalstatus = pd.DataFrame(encoded_maritalstatus, columns=encoder.get_feature_names_out(['MaritalStatus']))

#Encode Attrition
encoded_attrition = encoder.fit_transform(EmpleadosAttrition[['Attrition']])
encoded_df_attrition = pd.DataFrame(encoded_attrition, columns=encoder.get_feature_names_out(['Attrition']))


In [14]:
#Unirlos al Dataframe

EmpleadosAttrition = pd.concat([EmpleadosAttrition,
                                encoded_df_businesstravel,
                                encoded_df_department,
                                encoded_df_educationfield,
                                encoded_df_gender,
                                encoded_df_jobrole,
                                encoded_df_maritalstatus,
                                encoded_df_attrition], axis = 1)



In [15]:
EmpleadosAttrition_df=EmpleadosAttrition.drop(['BusinessTravel','Department','EducationField',
                                               'Gender','JobRole','MaritalStatus','Attrition',
                                               'HiringDate','OverTime','DistanceFromHome_km',
                                               'Attrition_No'],axis=1)

In [16]:
EmpleadosAttrition_df

Age  DistanceFromHome  Education  EnvironmentSatisfaction  \
0     50                 1          2                        4   
1     36                 6          2                        2   
2     21                 7          1                        2   
3     52                 7          4                        2   
4     33                15          1                        2   
..   ...               ...        ...                      ...   
395   33                14          3                        3   
396   31                20          3                        2   
397   37                11          3                        2   
398   38                 4          2                        4   
399   33                14          3                        4   

     JobInvolvement  JobLevel  JobSatisfaction  MonthlyIncome  \
0                 3         4                4          17399   
1                 3         2                2           4941   
2                 3         1                2           2679   
3                 3         3                2          10445   
4                 3         3                3          13610   
..              ...       ...              ...            ...   
395               3         1                4           2436   
396               1         2                3           4559   
397               3         3                4          12185   
398               3         1                3           3306   
399               3         1                2           2756   

     NumCompaniesWorked  PercentSalaryHike  ...  \
0                     9                 22  ...   
1                     6                 20  ...   
2                     1                 13  ...   
3                     7                 19  ...   
4                     7                 12  ...   
..                  ...                ...  ...   
395                   5                 13  ...   
396                   3                 11  ...   
397                   1                 14  ...   
398                   7                 19  ...   
399                   1                 13  ...   

     JobRole_Manufacturing Director  JobRole_Research Director  \
0                               0.0                        1.0   
1                               1.0                        0.0   
2                               0.0                        0.0   
3                               0.0                        0.0   
4                               0.0                        0.0   
..                              ...                        ...   
395                             0.0                        0.0   
396                             0.0                        0.0   
397                             0.0                        1.0   
398                             0.0                        0.0   
399                             0.0                        0.0   

     JobRole_Research Scientist  JobRole_Sales Executive  \
0                           0.0                      0.0   
1                           0.0                      0.0   
2                           0.0                      0.0   
3                           0.0                      0.0   
4                           0.0                      0.0   
..                          ...                      ...   
395                         0.0                      0.0   
396                         0.0                      1.0   
397                         0.0                      0.0   
398                         0.0                      0.0   
399                         1.0                      0.0   

     JobRole_Sales Representative  MaritalStatus_Divorced  \
0                             0.0                     1.0   
1                             0.0                     1.0   
2                             1.0                     0.0   
3                             0.0                     0.0   

In [17]:
corr_matrix = EmpleadosAttrition_df.corr()

In [18]:
corr_matrix['Attrition_Yes'].sort_values(ascending = False)

Attrition_Yes                        1.000000
MaritalStatus_Single                 0.205849
JobRole_Sales Representative         0.191294
Year                                 0.176001
EducationField_Technical Degree      0.129104
JobRole_Laboratory Technician        0.125264
Department_Sales                     0.066116
DistanceFromHome                     0.052732
EducationField_Human Resources       0.043404
BusinessTravel_Travel_Rarely         0.042755
BusinessTravel_Travel_Frequently     0.035387
JobRole_Human Resources              0.032714
Gender_Female                        0.028839
Department_Human Resources           0.023389
EducationField_Marketing             0.016768
MaritalStatus_nan                    0.010609
JobRole_Research Scientist           0.007977
JobRole_Sales Executive             -0.003115
EducationField_Other                -0.004275
PerformanceRating                   -0.006471
NumCompaniesWorked                  -0.009082
WorkLifeBalance                     -0.021723
EducationField_Life Sciences        -0.027457
Gender_Male                         -0.028839
RelationshipSatisfaction            -0.030945
JobRole_Manufacturing Director      -0.042404
BusinessTravel_nan                  -0.044677
EducationField_Medical              -0.054144
Education                           -0.055531
PercentSalaryHike                   -0.060880
YearsSinceLastPromotion             -0.069000
TrainingTimesLastYear               -0.070884
Department_Research & Development   -0.072269
JobRole_Manager                     -0.089885
MaritalStatus_Married               -0.094734
BusinessTravel_Non-Travel           -0.100698
JobRole_Healthcare Representative   -0.103274
MaritalStatus_Divorced              -0.107869
JobRole_Research Director           -0.116263
EnvironmentSatisfaction             -0.124327
JobSatisfaction                     -0.164957
JobInvolvement                      -0.166785
YearsAtCompany                      -0.176001
MonthlyIncome_norm                  -0.194936
MonthlyIncome                       -0.194936
YearsInCurrentRole                  -0.203918
Age                                 -0.212121
TotalWorkingYears                   -0.213329
JobLevel                            -0.214266
Name: Attrition_Yes, dtype: float64

In [19]:
selected_variables = corr_matrix [corr_matrix['Attrition_Yes']>=0.1]
selected_variables = selected_variables['Attrition_Yes']

In [20]:
selected_variables= selected_variables.index

In [21]:
EmpleadosAttritionFinal = EmpleadosAttrition[selected_variables]
EmpleadosAttritionFinal

Year  EducationField_Technical Degree  JobRole_Laboratory Technician  \
0    2013                              0.0                            0.0   
1    2015                              0.0                            0.0   
2    2017                              0.0                            0.0   
3    2010                              0.0                            0.0   
4    2011                              0.0                            0.0   
..    ...                              ...                            ...   
395  2013                              0.0                            1.0   
396  2016                              0.0                            0.0   
397  2008                              0.0                            0.0   
398  2018                              0.0                            1.0   
399  2010                              0.0                            0.0   

     JobRole_Sales Representative  MaritalStatus_Single  Attrition_Yes  
0                             0.0                   0.0            0.0  
1                             0.0                   0.0            0.0  
2                             1.0                   1.0            1.0  
3                             0.0                   1.0            0.0  
4                             0.0                   0.0            1.0  
..                            ...                   ...            ...  
395                           0.0                   0.0            1.0  
396                           0.0                   0.0            1.0  
397                           0.0                   0.0            0.0  
398                           0.0                   0.0            0.0  
399                           0.0                   0.0            0.0  

[400 rows x 6 columns]

# PCA

In [24]:
from sklearn.decomposition import PCA

In [25]:
pca = PCA()

In [27]:
pca.fit(EmpleadosAttritionFinal)

PCA()

In [28]:
print(pca.components_)

[[-0.99983821  0.00232609 -0.00753269 -0.00713163 -0.00952204 -0.01094862]
 [-0.01291335  0.00907026 -0.09372225  0.13096914  0.91805571  0.36192252]
 [-0.01058972  0.03641518  0.83503746 -0.0459008  -0.11916134  0.53382387]
 [-0.00155942  0.2119759  -0.50883489  0.21399715 -0.36757013  0.71780796]
 [-0.00259222  0.58270274  0.1833912   0.74761841  0.00892856 -0.26039483]
 [ 0.00595867  0.7836517  -0.03642211 -0.61315681  0.08772742 -0.02950516]]


In [29]:
print(pca.explained_variance_ratio_)

[0.98421379 0.00581905 0.00407301 0.00316017 0.00149125 0.00124274]


In [30]:
EmpleadosAttritionPCA = pca.transform(EmpleadosAttritionFinal)

In [31]:
EmpleadosAttritionPCA

array([[-2.24610716e+00, -3.36550950e-01, -2.17869810e-01,
         4.02461417e-02, -7.48443239e-02, -4.73195119e-03],
       [-4.24578358e+00, -3.62377646e-01, -2.39049240e-01,
         3.71272941e-02, -8.00287582e-02,  7.18538193e-03],
       [-6.27306229e+00,  1.02274303e+00,  1.08533067e-01,
         5.98243430e-01,  4.10938942e-01, -5.35831833e-01],
       ...,
       [ 2.75308389e+00, -2.71984211e-01, -1.64921234e-01,
         4.80432606e-02, -6.18832380e-02, -3.45252840e-02],
       [-7.25283090e+00, -4.94839940e-01,  5.64219073e-01,
        -4.76385863e-01,  9.55857879e-02, -1.13607331e-02],
       [ 7.53407467e-01, -2.97810907e-01, -1.86100665e-01,
         4.49244130e-02, -6.70676723e-02, -2.26079509e-02]])

In [32]:
EmpleadosAttritionFinal['PC1'] = EmpleadosAttritionPCA[:,0]

<ipython-input-32-7158fa31e4df>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  EmpleadosAttritionFinal['PC1'] = EmpleadosAttritionPCA[:,0]


In [33]:
EmpleadosAttritionFinal

Year  EducationField_Technical Degree  JobRole_Laboratory Technician  \
0    2013                              0.0                            0.0   
1    2015                              0.0                            0.0   
2    2017                              0.0                            0.0   
3    2010                              0.0                            0.0   
4    2011                              0.0                            0.0   
..    ...                              ...                            ...   
395  2013                              0.0                            1.0   
396  2016                              0.0                            0.0   
397  2008                              0.0                            0.0   
398  2018                              0.0                            1.0   
399  2010                              0.0                            0.0   

     JobRole_Sales Representative  MaritalStatus_Single  Attrition_Yes  \
0                             0.0                   0.0            0.0   
1                             0.0                   0.0            0.0   
2                             1.0                   1.0            1.0   
3                             0.0                   1.0            0.0   
4                             0.0                   0.0            1.0   
..                            ...                   ...            ...   
395                           0.0                   0.0            1.0   
396                           0.0                   0.0            1.0   
397                           0.0                   0.0            0.0   
398                           0.0                   0.0            0.0   
399                           0.0                   0.0            0.0   

          PC1  
0   -2.246107  
1   -4.245784  
2   -6.273062  
3    0.743885  
4   -0.257379  
..        ...  
395 -2.264588  
396 -5.256570  
397  2.753084  
398 -7.252831  
399  0.753407  

[400 rows x 7 columns]

# Guardar el archivo resultante

In [37]:
EmpleadosAttritionFinal.to_csv('EmpleadosAttritionFinal.csv', index=False)
files.download('EmpleadosAttritionFinal.csv')

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>